In [1]:
#Q1(1)
lst=['Smita', 'Vedant', 'Yashraj','Viraj', 'Priyanka']
lst1=['Porsche','Volvo','Range Rover','Porsche']

lst_1=lst.append('Swift02')
print(lst_1,lst)

lst_2=lst.extend(lst1)
print(lst_2,lst)

lst_3=lst1.insert(2,'Iphone')
print(lst_3,lst1)

lst_4=lst1.remove('Iphone')
print(lst_4,lst1)

print(lst1.pop(2))

print(lst.index('Viraj'))

print(lst1.count('Porsche'))

lst1.sort()
print(lst1)

lst.reverse()
print(lst)

# clear should be last
lst1.clear()
print(lst1)

None ['Smita', 'Vedant', 'Yashraj', 'Viraj', 'Priyanka', 'Swift02']
None ['Smita', 'Vedant', 'Yashraj', 'Viraj', 'Priyanka', 'Swift02', 'Porsche', 'Volvo', 'Range Rover', 'Porsche']
None ['Porsche', 'Volvo', 'Iphone', 'Range Rover', 'Porsche']
None ['Porsche', 'Volvo', 'Range Rover', 'Porsche']
Range Rover
3
2
['Porsche', 'Porsche', 'Volvo']
['Porsche', 'Range Rover', 'Volvo', 'Porsche', 'Swift02', 'Priyanka', 'Viraj', 'Yashraj', 'Vedant', 'Smita']
[]


In [14]:
#Q1(2)
students=("Swaraj", "Khali", "Rakesh")
students[1]="Priya"
#Tupples are irreplaceble , it gives error


TypeError: 'tuple' object does not support item assignment

In [2]:
#Q1(3)
integer={"2","3","8","7","3","4","2"}
print(integer)

{'8', '7', '4', '2', '3'}


 Set doesnot see repeated values, order is unpredictable, keep only unique elements


In [3]:
""" Set doesnot see repeated values, order is unpredictable, keep only unique elements"""
#Q1(4)
person={
        "name" : "Pratik",
        "age" : 23,
        "City" : "Pune"
        }

person["age"]=24

person["email"]="Pratikgharge11@gmail.com"

print(person)

for key, value in person.items():
    print(key, ":" , value)
    

{'name': 'Pratik', 'age': 24, 'City': 'Pune', 'email': 'Pratikgharge11@gmail.com'}
name : Pratik
age : 24
City : Pune
email : Pratikgharge11@gmail.com


In [4]:
#Q1(5)
age=int(input("Enter Your Age :"))

print("\n-----ELECTION COMISSION OF INDIA-----")
if age>=18:
    print("YOU ARE ELIGIBLE TO VOTE !")
    
else:
    print("YOU ARE NOT ELIGIBLE TO VOTE !")
    



Enter Your Age : 26



-----ELECTION COMISSION OF INDIA-----
YOU ARE ELIGIBLE TO VOTE !


In [5]:
#Q1(6)
marks=int(input("Enter your marks :"))

if marks>=90:
    print("GRADE A")
    
elif 90>marks>=75:
    print("GRADE B")
    
elif 75>marks>=50:
    print("GRADE C")
    
else:
    print("FAIL !")
    


Enter your marks : 89


GRADE B


In [19]:
#Q1(7)
num=int(input("Enter the number :"))

if num>0:
    print("The number is Positive")
    
    if num%2==0:
        print("The number is also EVEN !")
    
    else:
        print("The number is also ODD !")
        
elif num==0:
    print("The number is ZERO !")
    
else:
    print("The number is NEGATIVE !")
    
 
 


Enter the number : 58


The number is Positive
The number is also EVEN !


In [20]:
#Q2(1)
import numpy as np

scalar=np.array(5)
print("Scalar :",scalar)

one_d=np.array([1,2,3,4,5])
print("1D Array :",one_d)

two_d=np.array([[10,20,30],
                [40,50,60]])
print("\n2D Array :",two_d)



Scalar : 5
1D Array : [1 2 3 4 5]

2D Array : [[10 20 30]
 [40 50 60]]


In [21]:
#Q2(2)
import numpy as np

arr=np.random.randint(0,101,size=(4,4))
print(arr)



[[93 87 40  1]
 [33  1 37 25]
 [10 47 17 73]
 [ 2 42 10 29]]


In [22]:
#Q2(3)
import numpy as np

two_d=np.array([
    [10,20,30],
    [40,50,60],
    [70,80,90]
    ])
print("2D Array :",two_d)

import pandas as pd

df=pd.DataFrame(two_d)
df

df=pd.DataFrame(two_d,index=['Row1','Row2','Row3'],columns=['Column A','Column B','Column C'])
print(df)



2D Array : [[10 20 30]
 [40 50 60]
 [70 80 90]]
      Column A  Column B  Column C
Row1        10        20        30
Row2        40        50        60
Row3        70        80        90


In [3]:
#Q3
import numpy as np
import pandas as pd

data = {
    "Name": ["pratik","Ayush","Saurabh","Gudya","Harshad","Viraj","Shreyas","Omkar","Yash","Radhe"],
    "Age": [21,22,23,25,24,31,21,22,23,24],
    "City": ["Pune","Mumbai","Mumbai","Satara","Sangli","Kolhapur","Akola","Nagpur","Beed","Thane"],
    "Salary": [np.nan,2000,3000,np.nan,4000,2000,5000,np.nan,5000,2500]
}

# Create DataFrame
df = pd.DataFrame(data)

# Find mean salary
mean_salary = df["Salary"].mean()

# Fill missing values with mean
df["Salary"] = df["Salary"].fillna(mean_salary)

print("\n-----Data Frame-----")
print(df)

print("\n-----Info-----")
print(df.info())

print("\n-----Description-----")
print(df.describe())

print("\n-----Name and City Columns-----")
print(df[["Name", "City"]])

# Dropping column
df_drop = df.drop("City", axis=1)

print("\n-----After Dropping City Column-----")
print(df_drop)

# Removing duplicate rows
df_duplicate = df.drop_duplicates()

print("\n-----After Removing Duplicate Rows-----")
print(df_duplicate)


-----Data Frame-----
      Name  Age      City       Salary
0   pratik   21      Pune  3357.142857
1    Ayush   22    Mumbai  2000.000000
2  Saurabh   23    Mumbai  3000.000000
3    Gudya   25    Satara  3357.142857
4  Harshad   24    Sangli  4000.000000
5    Viraj   31  Kolhapur  2000.000000
6  Shreyas   21     Akola  5000.000000
7    Omkar   22    Nagpur  3357.142857
8     Yash   23      Beed  5000.000000
9    Radhe   24     Thane  2500.000000

-----Info-----
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   Name    10 non-null     object 
 1   Age     10 non-null     int64  
 2   City    10 non-null     object 
 3   Salary  10 non-null     float64
dtypes: float64(1), int64(1), object(2)
memory usage: 452.0+ bytes
None

-----Description-----
            Age       Salary
count  10.00000    10.000000
mean   23.60000  3357.142857
std     2.91357  1072.750507